# Generated by Django 6.0.4 on 2026-04-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('directorate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('directorate_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'directorates',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directorate', models.ForeignKey(blank=True, db_column='directorate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.directorate')),
            ],
            options={
                'db_table': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nik', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(blank=True, max_length=50, null=True)),
                ('special_position', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_supervisor', models.ForeignKey(blank=True, db_column='direct_supervisor_nik', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('division', models.ForeignKey(blank=True, db_column='division_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.division')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(db_column='nik', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('training_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='api.employee')),
            ],
            options={
                'db_table': 'training_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
