# Generated by Django 6.0.4 on 2026-04-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('course_category_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_categories',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_city', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('price_estimation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hotel_star', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(blank=True, db_column='course_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coursecategory')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
