# Generated by Django 6.0.4 on 2026-04-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursecategory_hotel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaPeriod',
            fields=[
                ('tna_period_id', models.IntegerField(primary_key=True, serialize=False)),
                ('period_code', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('period_name', models.CharField(blank=True, max_length=50, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tna_periods',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('web_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='TnaMaster',
            fields=[
                ('tna_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('group_name', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('course_category', models.ForeignKey(db_column='course_category_id', on_delete=django.db.models.deletion.CASCADE, to='api.coursecategory')),
                ('tna_period', models.ForeignKey(db_column='tna_period_id', on_delete=django.db.models.deletion.CASCADE, to='api.tnaperiod')),
            ],
            options={
                'db_table': 'tna_master',
                'constraints': [models.CheckConstraint(condition=models.Q(('group_name__gte', 1), ('group_name__lte', 6)), name='tna_master_group_name_check'), models.CheckConstraint(condition=models.Q(('created_by__in', [200335, 200331, 200329])), name='tna_master_created_by_check')],
            },
        ),
    ]
