# Generated by Django 6.0.4 on 2026-04-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tnaperiod_vendor_tnamaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaParticipant',
            fields=[
                ('tna_participant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tna_participant',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tnamaster',
            name='tna_master_group_name_check',
        ),
        migrations.RemoveConstraint(
            model_name='tnamaster',
            name='tna_master_created_by_check',
        ),
        migrations.AlterField(
            model_name='tnamaster',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='tnaperiod',
            name='period_code',
            field=models.CharField(default='DUMMY', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tnaperiod',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tnaperiod',
            name='tna_period_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tnaperiod',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tnamaster',
            constraint=models.CheckConstraint(condition=models.Q(('group_name__gte', 1), ('group_name__lte', 6)), name='tna_master_group_name_check_new'),
        ),
        migrations.AddConstraint(
            model_name='tnamaster',
            constraint=models.CheckConstraint(condition=models.Q(('created_by__in', [200335, 200331, 200329])), name='tna_master_created_by_check_new'),
        ),
        migrations.AlterModelTable(
            name='tnaperiod',
            table='tna_period',
        ),
        migrations.AddField(
            model_name='tnaparticipant',
            name='nik',
            field=models.ForeignKey(db_column='nik', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='tnaparticipant',
            name='tna',
            field=models.ForeignKey(db_column='tna_id', on_delete=django.db.models.deletion.CASCADE, to='api.tnamaster'),
        ),
    ]
