# Generated by Django 6.0.4 on 2026-04-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tnaparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tnamaster',
            name='tna_master_created_by_check_new',
        ),
    ]
