# Generated by Django 6.0.4 on 2026-04-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tnamaster_tna_master_created_by_check_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_topic', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status_training', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Open', 'Open'), ('Draft', 'Draft')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'training_events',
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('material', models.CharField(blank=True, max_length=500, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent')),
            ],
            options={
                'db_table': 'event_schedule',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(blank=True, max_length=25, null=True)),
                ('l1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('l2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nik', models.ForeignKey(db_column='nik', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent')),
            ],
            options={
                'db_table': 'event_participants',
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('event_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=150)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent')),
            ],
            options={
                'db_table': 'event_location',
            },
        ),
        migrations.CreateModel(
            name='EventCost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_center', models.CharField(blank=True, max_length=25, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('room_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('training_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sppd_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_type', models.CharField(blank=True, choices=[('Estimate Cost', 'Estimate Cost'), ('Actual Cost', 'Actual Cost')], max_length=50, null=True)),
                ('status_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent')),
            ],
            options={
                'db_table': 'event_cost',
            },
        ),
        migrations.CreateModel(
            name='TrainingMaster',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_code', models.CharField(max_length=20)),
                ('training_type', models.CharField(blank=True, choices=[('Inhouse Training', 'Inhouse Training'), ('Public Training', 'Public Training'), ('Online Training', 'Online Training'), ('Knowledge Sharing', 'Knowledge Sharing')], max_length=25, null=True)),
                ('training_category', models.CharField(blank=True, choices=[('ESG', 'ESG'), ('Hard Skill', 'Hard Skill'), ('Soft Skill', 'Soft Skill')], max_length=50, null=True)),
                ('training_title', models.CharField(blank=True, max_length=150, null=True)),
                ('training_description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('course_category', models.ForeignKey(db_column='course_category_id', on_delete=django.db.models.deletion.CASCADE, to='api.coursecategory')),
                ('pic', models.ForeignKey(db_column='pic_nik', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
            options={
                'db_table': 'training_master',
            },
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='training',
            field=models.ForeignKey(db_column='training_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingmaster'),
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Report', 'Report'), ('Form IHT', 'Form IHT'), ('All Document', 'All Document')], max_length=50)),
                ('file_name', models.CharField(max_length=150)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.trainingevent')),
            ],
            options={
                'db_table': 'event_documents',
                'constraints': [models.CheckConstraint(condition=models.Q(('file_url__icontains', 'drive.google.com')), name='event_documents_file_url_check'), models.CheckConstraint(condition=models.Q(('uploaded_by__in', [200335, 200331, 200329])), name='event_documents_uploaded_by_check')],
            },
        ),
    ]
