# Generated by Django 6.0.4 on 2026-04-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trainingevent_eventschedule_eventparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventdocument',
            name='event_documents_file_url_check',
        ),
        migrations.RemoveConstraint(
            model_name='eventdocument',
            name='event_documents_uploaded_by_check',
        ),
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='participant_id',
            new_name='event_participant_id',
        ),
        migrations.RenameField(
            model_name='eventschedule',
            old_name='instructor',
            new_name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='room_cost',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='status_cost',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'nik')},
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='material',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='status_training',
        ),
        migrations.AddField(
            model_name='eventcost',
            name='room_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventcost',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='eventcost',
            name='total_room_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='doc_type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Certificate', 'Certificate'), ('Attendance', 'Attendance'), ('Training Report', 'Training Report'), ('Sertifikat G-Drive', 'Sertifikat G-Drive')], default='Invoice', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='material_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='hotel',
            field=models.ForeignKey(blank=True, db_column='hotel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hotel'),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='event',
            field=models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='sppd_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='training_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='file_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by_nik', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='event',
            field=models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='pic',
            field=models.ForeignKey(db_column='pic_nik', on_delete=django.db.models.deletion.CASCADE, related_name='managed_trainings', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_type',
            field=models.CharField(blank=True, choices=[('Inhouse Training', 'Inhouse Training'), ('Public Training', 'Public Training'), ('E-Learning', 'E-Learning')], max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventdocument',
            constraint=models.CheckConstraint(condition=models.Q(('file_url__contains', 'drive.google.com')), name='check_google_drive_link'),
        ),
        migrations.AddConstraint(
            model_name='eventdocument',
            constraint=models.CheckConstraint(condition=models.Q(('uploaded_by__in', [200335, 200331, 200329])), name='check_authorized_uploader'),
        ),
        migrations.AlterModelTable(
            name='eventcost',
            table='event_costs',
        ),
        migrations.AlterModelTable(
            name='eventlocation',
            table='event_locations',
        ),
        migrations.AlterModelTable(
            name='eventschedule',
            table='event_schedules',
        ),
        migrations.RemoveField(
            model_name='eventdocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='eventdocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='attendance_status',
        ),
    ]
