# Generated by Django 6.0.4 on 2026-04-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_eventdocument_event_documents_file_url_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcost',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api.trainingevent'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='doc_type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Form IHT', 'Form IHT'), ('All Document', 'All Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingmaster',
            name='training_type',
            field=models.CharField(blank=True, choices=[('Inhouse Training', 'Inhouse Training'), ('Public Training', 'Public Training'), ('E-Learning', 'E-Learning'), ('Knowledge Sharing', 'Knowledge Sharing')], max_length=25, null=True),
        ),
    ]
