# Generated by Django 6.0.4 on 2026-04-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_eventcost_event_alter_eventdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingevent',
            name='hotel',
        ),
    ]
