# Generated by Django 6.0.4 on 2026-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_trainingevent_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
