# Generated by Django 6.0.4 on 2026-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_eventlocation_address_eventlocation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='attendance_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
