# Generated by Django 6.0.4 on 2026-04-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_eventparticipant_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='remarks',
        ),
    ]
