# Generated by Django 6.0.4 on 2026-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_eventparticipant_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcost',
            name='room_per_night',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='eventcost',
            name='total_room_cost',
        ),
        migrations.AddField(
            model_name='eventcost',
            name='cost_center',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='eventcost',
            name='cost_type',
            field=models.CharField(choices=[('Estimate Cost', 'Estimate Cost'), ('Actual Cost', 'Actual Cost')], default='Estimate Cost', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcost',
            name='currency',
            field=models.CharField(default='IDR', max_length=10),
        ),
        migrations.AddField(
            model_name='eventcost',
            name='room_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='eventcost',
            name='status_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='sppd_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='training_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name='eventcost',
            constraint=models.CheckConstraint(condition=models.Q(('cost_type__in', ['Estimate Cost', 'Actual Cost'])), name='event_cost_cost_type_check'),
        ),
    ]
