# Generated by Django 6.0.4 on 2026-04-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_eventcost_room_per_night_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdocument',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='document_type',
            field=models.CharField(default='All Document', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='file_name',
            field=models.CharField(default='document.pdf', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='file_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', default=200335, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
    ]
