# Generated by Django 6.0.4 on 2026-04-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_eventdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='enable_course_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='enable_evaluations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='enable_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
