# Generated by Django 6.0.4 on 2026-04-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trainingevent_enable_course_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcost',
            name='cost_type',
            field=models.CharField(choices=[('Estimate Cost Center', 'Estimate Cost Center'), ('Actual Cost Center', 'Actual Cost Center')], max_length=50),
        ),
    ]
