# Generated by Django 6.0.4 on 2026-04-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_eventcost_cost_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
