# Generated by Django 6.0.4 on 2026-05-03 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_trainingdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('l1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('l2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('form_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'evaluation_forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=20)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_type', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestionOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_question_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('training_name', models.CharField(blank=True, max_length=200, null=True)),
                ('template', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_results',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='documentation_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='cost_type',
            field=models.CharField(choices=[('Estimate Cost', 'Estimate Cost'), ('Actual Cost', 'Actual Cost')], max_length=50),
        ),
        migrations.CreateModel(
            name='AiAdminConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_admin_config',
            },
        ),
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.BigIntegerField(blank=True, null=True)),
                ('role', models.CharField(default='Employee', max_length=100)),
                ('division_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='AiFaq',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sequence', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_faq',
            },
        ),
        migrations.CreateModel(
            name='AiChatLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.BigIntegerField(blank=True, null=True)),
                ('role', models.CharField(default='Employee', max_length=50)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_faq_triggered', models.BooleanField(default=False)),
                ('is_out_of_scope', models.BooleanField(default=False)),
                ('is_unanswered', models.BooleanField(default=False)),
                ('redirected_to_wa', models.BooleanField(default=False)),
                ('is_authorized', models.BooleanField(default=True)),
                ('query_executed', models.TextField(blank=True, null=True)),
                ('context_sent', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.aichatsession')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aifaq')),
            ],
            options={
                'db_table': 'ai_chat_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiUnauthorizedAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.BigIntegerField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('attempted_access', models.TextField()),
                ('division_requested', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(blank=True, db_column='log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aichatlog')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_unauthorized_attempts',
            },
        ),
    ]
