# Generated by Django 6.0.4 on 2026-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_evaluationanswer_evaluationform_evaluationquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_name', models.CharField(max_length=150)),
                ('start_date_budget', models.DateField()),
                ('end_date_budget', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='documentation_url',
        ),
    ]
