# Generated by Django 5.2 on 2026-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_budget_remove_trainingevent_documentation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiadminconfig',
            name='description',
        ),
    ]
