# Generated by Django 5.2 on 2026-05-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_eventdocument_check_authorized_uploader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatlog',
            name='faq',
        ),
        migrations.DeleteModel(
            name='AiFaq',
        ),
    ]
