# Generated by Django 6.0.4 on 2026-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_aifaq_created_by_remove_aifaq_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['hotel_id']},
        ),
        migrations.RemoveConstraint(
            model_name='eventdocument',
            name='check_authorized_uploader',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_phone',
            new_name='sales_phone_number',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='documentation_url',
        ),
        migrations.AddField(
            model_name='hotel',
            name='sales_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
