# Generated by Django 5.2 on 2026-07-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatlog',
            name='is_faq_triggered',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
